# Generated by Django 5.2.1 on 2025-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
