# Generated by Django 5.2.1 on 2025-05-18 22:45

import colaboradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_colaborador_grupo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='colaborador',
            managers=[
                ('objects', colaboradores.models.ColaboradorManager()),
            ],
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
