# Generated by Django 5.2.1 on 2025-05-18 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_colaborador_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionarioResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('pergunta_1', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_2', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_3', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_4', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_5', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_6', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_7', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_8', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_9', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_10', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_11', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_12', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_13', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_14', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_15', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_16', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_17', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_18', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_19', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_20', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
